SIMULATED_PATIENTS = [
    {
        "age": 67,
        "heart_rate": 130,
        "spo2": 91,
        "systolic_bp": 145,
        "temperature": 37.0,
        "respiratory_rate": 24,
        "pain_level": 8,
        "chest_pain": 1,
        "shortness_breath": 1,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 1,
        "diabetes": 0,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Severe chest pain",
        "patient_words": "I feel pressure in my chest and I am struggling to breathe."
    },
    {
        "age": 74,
        "heart_rate": 118,
        "spo2": None,
        "systolic_bp": 105,
        "temperature": 37.2,
        "respiratory_rate": 22,
        "pain_level": 3,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": None,
        "diabetes": None,
        "hypertension": None,
        "previous_stroke": None,
        "history_available": False,
        "chief_complaint": "I don't feel right",
        "patient_words": "I just feel weak and strange."
    },
    {
        "age": 3,
        "heart_rate": 140,
        "spo2": 94,
        "systolic_bp": 90,
        "temperature": 38.5,
        "respiratory_rate": 32,
        "pain_level": 4,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": False,
        "chief_complaint": "Fever and poor feeding",
        "patient_words": "My child has fever and is not eating normally."
    },
    {
        "age": 58,
        "heart_rate": 126,
        "spo2": 89,
        "systolic_bp": 92,
        "temperature": 38.1,
        "respiratory_rate": 30,
        "pain_level": 7,
        "chest_pain": 0,
        "shortness_breath": 1,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Severe breathing difficulty",
        "patient_words": "I cannot catch my breath."
    },
    {
        "age": 61,
        "heart_rate": 108,
        "spo2": 95,
        "systolic_bp": 178,
        "temperature": 36.8,
        "respiratory_rate": 20,
        "pain_level": 6,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 1,
        "weakness": 1,
        "speech_problem": 1,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 1,
        "history_available": True,
        "chief_complaint": "Sudden speech difficulty",
        "patient_words": "My speech suddenly became difficult."
    },
    {
        "age": 42,
        "heart_rate": 102,
        "spo2": 97,
        "systolic_bp": 132,
        "temperature": 39.1,
        "respiratory_rate": 23,
        "pain_level": 5,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "High fever and weakness",
        "patient_words": "I have had a high fever since yesterday."
    },
    {
        "age": 29,
        "heart_rate": 88,
        "spo2": 99,
        "systolic_bp": 121,
        "temperature": 36.7,
        "respiratory_rate": 16,
        "pain_level": 2,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Minor ankle injury",
        "patient_words": "I twisted my ankle while playing."
    },
    {
        "age": 35,
        "heart_rate": 94,
        "spo2": 98,
        "systolic_bp": 126,
        "temperature": 37.1,
        "respiratory_rate": 18,
        "pain_level": 5,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Abdominal pain",
        "patient_words": "I have had abdominal pain for several hours."
    },
    {
        "age": 81,
        "heart_rate": 122,
        "spo2": 92,
        "systolic_bp": 110,
        "temperature": 38.0,
        "respiratory_rate": 26,
        "pain_level": 4,
        "chest_pain": 0,
        "shortness_breath": 1,
        "confusion": 1,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 1,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Confusion and weakness",
        "patient_words": "I feel unusually tired and confused."
    },
    {
        "age": 19,
        "heart_rate": 110,
        "spo2": 96,
        "systolic_bp": 118,
        "temperature": 37.8,
        "respiratory_rate": 21,
        "pain_level": 6,
        "chest_pain": 1,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": False,
        "chief_complaint": "Chest discomfort",
        "patient_words": "I have a strange pressure in my chest."
    },
    {
        "age": 52,
        "heart_rate": 116,
        "spo2": 93,
        "systolic_bp": 98,
        "temperature": 38.7,
        "respiratory_rate": 27,
        "pain_level": 7,
        "chest_pain": 0,
        "shortness_breath": 1,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 1,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Fever with breathing difficulty",
        "patient_words": "My fever is getting worse and breathing is harder."
    },
    {
        "age": 67,
        "heart_rate": 86,
        "spo2": 97,
        "systolic_bp": 138,
        "temperature": 36.9,
        "respiratory_rate": 18,
        "pain_level": 2,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 1,
        "diabetes": 0,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Routine medication concern",
        "patient_words": "I am worried about a medication side effect."
    },
    {
        "age": 7,
        "heart_rate": 132,
        "spo2": 96,
        "systolic_bp": 100,
        "temperature": 38.8,
        "respiratory_rate": 29,
        "pain_level": 5,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Fever and weakness",
        "patient_words": "My child has been weak with a fever."
    },
    {
        "age": 46,
        "heart_rate": 90,
        "spo2": 98,
        "systolic_bp": 130,
        "temperature": 36.8,
        "respiratory_rate": 17,
        "pain_level": 1,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Minor headache",
        "patient_words": "I have a mild headache."
    },
    {
        "age": 72,
        "heart_rate": 124,
        "spo2": 90,
        "systolic_bp": 100,
        "temperature": 37.6,
        "respiratory_rate": 28,
        "pain_level": 5,
        "chest_pain": 0,
        "shortness_breath": 1,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 1,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Breathing difficulty",
        "patient_words": "I am becoming increasingly short of breath."
    },
    {
        "age": 31,
        "heart_rate": 104,
        "spo2": 97,
        "systolic_bp": 115,
        "temperature": 37.0,
        "respiratory_rate": 19,
        "pain_level": 8,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": False,
        "chief_complaint": "Severe back pain",
        "patient_words": "My back pain is extremely severe."
    },
    {
        "age": 55,
        "heart_rate": 128,
        "spo2": 94,
        "systolic_bp": 88,
        "temperature": 39.0,
        "respiratory_rate": 29,
        "pain_level": 8,
        "chest_pain": 0,
        "shortness_breath": 1,
        "confusion": 1,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Severe infection symptoms",
        "patient_words": "I feel extremely weak and feverish."
    },
    {
        "age": 24,
        "heart_rate": 82,
        "spo2": 99,
        "systolic_bp": 119,
        "temperature": 36.6,
        "respiratory_rate": 16,
        "pain_level": 3,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 0,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Minor laceration",
        "patient_words": "I cut my hand while cooking."
    },
    {
        "age": 69,
        "heart_rate": 112,
        "spo2": 95,
        "systolic_bp": 142,
        "temperature": 37.4,
        "respiratory_rate": 22,
        "pain_level": 6,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 1,
        "diabetes": 1,
        "hypertension": 1,
        "previous_stroke": 0,
        "history_available": False,
        "chief_complaint": "Weakness",
        "patient_words": "I have felt unusually weak today."
    },
    {
        "age": 39,
        "heart_rate": 98,
        "spo2": 98,
        "systolic_bp": 124,
        "temperature": 38.3,
        "respiratory_rate": 20,
        "pain_level": 4,
        "chest_pain": 0,
        "shortness_breath": 0,
        "confusion": 0,
        "weakness": 1,
        "speech_problem": 0,
        "severe_bleeding": 0,
        "cardiac_history": 0,
        "diabetes": 0,
        "hypertension": 0,
        "previous_stroke": 0,
        "history_available": True,
        "chief_complaint": "Flu-like symptoms",
        "patient_words": "I have fever, body aches and fatigue."
    }
]